version: '3.8'

services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: cinema_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: cinema_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "cinema"
    volumes:
      - db_data:/var/lib/mysql



volumes:
  db_data:
